language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - extra-android-m2-repository

    # The BuildTools version
    - build-tools-25.0.2

    # The SDK version
    - android-21

  licenses:
    - android-sdk-license-.+

script:
  - ./gradlew test

before_install:
  - pip install --user codecov

after_success:
  - codecov


